### ISSUE TITLE
Error in ss.sumarize(input,1) from test/summarize.doctest

### ISSUE THREAD

**Issue by lukakostic** [thavelick/summarize#5]
import summarize

	ss = summarize.SimpleSummarizer()
	input = "NLTK is a python library for working human-written text. Summarize is a package 				 
    that uses NLTK to create summaries."
	ss.summarize(input, 1)

ss.summarize results in this error:

Traceback (most recent call last):
  File "SumTest.py", line 5, in <module>
    ss.summarize(input, 1)
  File "summarize.py", line 75, in summarize
    return " ".join(self.get_summarized(input, num_sentences))
  File "summarize.py", line 47, in get_summarized
    word_frequencies.items()[:100]]
TypeError: 'dict_items' object is not subscriptable

**Comment by lukakostic** [comment]
print(ss.summarize(input, 1)) is same error (guessing it returns a touple of strings or something but havent gotten to that stage yet due to the error)

**Comment by anjalibhavan** [comment]
I solved this using:
`most_frequent_words = [pair[0] for pair in list(word_frequencies.items())[:100]]`
Converted that word frequencies items to list, that is. However, after this I got another error:
`Error Sort in Python 3.x : TypeError: must use keyword argument for key function`
This was in the lambda function line, which I solved as follows:
`output_sentences.sort(key=lambda s1, s2: input.find(s1) - input.find(s2))`
After this, I NEXT got the following error:
`TypeError: <lambda>() missing 1 required positional argument: 's2'`

Did you mean to add a comma instead of the subtraction sign between the two input.find()? I wasn't too sure about this.

**Comment by anjalibhavan** [comment]
Alright, turns out that this is due to a Python 3 update. Tuple unpacking is not available anymore. Please update the code for running in Python 3+.

**Comment by jajuyash** [comment]
> Alright, turns out that this is due to a Python 3 update. Tuple unpacking is not available anymore. Please update the code for running in Python 3+.

Can you tell me how did you update the code for python 3?
